print('A'.rjust(8))
print('B B'.rjust(9))
print('C   C'.rjust(10))
print('D     D'.rjust(11))
print('E       E'.rjust(12))
print('D     D'.rjust(11))
print('C   C'.rjust(10))
print('B B'.rjust(9))
print('A'.rjust(8))